POST https://enigmatic-bayou-48219.herokuapp.com/api/v2/account/login
Content-Type: application/json

{
    "email": "mobile_test@warrenbrasil.com",
    "password": "Warren123!"
}



###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjoiNTgzNGFkM2MyMjdlYTVhYzdmYzBmZjAyIiwiYWNjZXNzVG9rZW5JZCI6IjVkOWU0YzQ4NTE5NzIwMDAxMWJkN2YxOSIsImFjY2Vzc1Rva2VuSGFzaCI6ImQzOWM3NTY3MGQ5MzU4NmU0NDNhZDJiMjNjMGVlMWQzZDViOTdhMDcyYzU3NmYzNjY5NTA3Mjk4ZDUzYzlmN2UiLCJpYXQiOjE1NzA2NTUzMDQsImV4cCI6MTU3MTI2MDEwNH0.k4GtMCxIX8xP-K0yNW3SGKVbL0qT40EF8h-y9gWUE04
GET https://enigmatic-bayou-48219.herokuapp.com/api/v2/portfolios/mine
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjoiNTgzNGFkM2MyMjdlYTVhYzdmYzBmZjAyIiwiYWNjZXNzVG9rZW5JZCI6IjVkOWU0YzQ4NTE5NzIwMDAxMWJkN2YxOSIsImFjY2Vzc1Rva2VuSGFzaCI6ImQzOWM3NTY3MGQ5MzU4NmU0NDNhZDJiMjNjMGVlMWQzZDViOTdhMDcyYzU3NmYzNjY5NTA3Mjk4ZDUzYzlmN2UiLCJpYXQiOjE1NzA2NTUzMDQsImV4cCI6MTU3MTI2MDEwNH0.k4GtMCxIX8xP-K0yNW3SGKVbL0qT40EF8h-y9gWUE04
Content-Type: application/json